# Generated by Django 3.2 on 2021-04-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='q_text',
            new_name='question',
        ),
    ]
